<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file project CDATA #REQUIRED>
<!ATTLIST file module CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult project CDATA #REQUIRED>
<!ATTLIST summaryresult module CDATA #REQUIRED>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.2">
    <summary>
        <summaryresult date="2006-11-14" filecount="121"
            module="statsvn" project="StatSvn" statvalue="610" type="checkstyle"/>
        <summaryresult date="2006-11-14" filecount="34" module="statsvn"
            project="StatSvn" statvalue="64" type="findbugs"/>
        <summaryresult date="2006-11-14" filecount="112"
            module="statsvn" project="StatSvn" statvalue="69" type="cobertura-line"/>
        <summaryresult date="2006-11-14" filecount="112"
            module="statsvn" project="StatSvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-14" filecount="8" module="statsvn"
            project="StatSvn" statvalue="14" type="pmd"/>
        <summaryresult date="2006-11-15" filecount="121"
            module="statsvn" project="StatSvn" statvalue="594" type="checkstyle"/>
        <summaryresult date="2006-11-15" filecount="30" module="statsvn"
            project="StatSvn" statvalue="52" type="findbugs"/>
        <summaryresult date="2006-11-15" filecount="112"
            module="statsvn" project="StatSvn" statvalue="69" type="cobertura-line"/>
        <summaryresult date="2006-11-15" filecount="112"
            module="statsvn" project="StatSvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-15" filecount="6" module="statsvn"
            project="StatSvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-11-16" filecount="121"
            module="statsvn" project="StatSvn" statvalue="439" type="checkstyle"/>
        <summaryresult date="2006-11-16" filecount="30" module="statsvn"
            project="StatSvn" statvalue="61" type="findbugs"/>
        <summaryresult date="2006-11-16" filecount="112"
            module="statsvn" project="StatSvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-16" filecount="112"
            module="statsvn" project="StatSvn" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-11-16" filecount="7" module="statsvn"
            project="StatSvn" statvalue="13" type="pmd"/>
        <summaryresult date="2006-11-17" filecount="121"
            module="statsvn" project="StatSvn" statvalue="393" type="checkstyle"/>
        <summaryresult date="2006-11-17" filecount="29" module="statsvn"
            project="StatSvn" statvalue="51" type="findbugs"/>
        <summaryresult date="2006-11-17" filecount="112"
            module="statsvn" project="StatSvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-17" filecount="112"
            module="statsvn" project="StatSvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-17" filecount="7" module="statsvn"
            project="StatSvn" statvalue="13" type="pmd"/>
        <summaryresult date="2006-11-18" filecount="122"
            module="statsvn" project="StatSvn" statvalue="165" type="checkstyle"/>
        <summaryresult date="2006-11-18" filecount="27" module="statsvn"
            project="StatSvn" statvalue="39" type="findbugs"/>
        <summaryresult date="2006-11-18" filecount="113"
            module="statsvn" project="StatSvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-18" filecount="113"
            module="statsvn" project="StatSvn" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-11-18" filecount="6" module="statsvn"
            project="StatSvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-11-19" filecount="122"
            module="statsvn" project="StatSvn" statvalue="165" type="checkstyle"/>
        <summaryresult date="2006-11-19" filecount="26" module="statsvn"
            project="StatSvn" statvalue="39" type="findbugs"/>
        <summaryresult date="2006-11-19" filecount="113"
            module="statsvn" project="StatSvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-19" filecount="113"
            module="statsvn" project="StatSvn" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-11-19" filecount="6" module="statsvn"
            project="StatSvn" statvalue="12" type="pmd"/>
    </summary>
    <file id="StatSvn-statsvn-net_sf_statsvn_output_package.html"
        module="statsvn" path="net/sf/statsvn/output/package.html" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="checkstyle"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_reportmodel_package.html"
        module="statsvn" path="net/sf/statsvn/reportmodel/package.html" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="checkstyle"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_reports_package.html"
        module="statsvn" path="net/sf/statsvn/reports/package.html" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="checkstyle"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_renderer_package.html"
        module="statsvn" path="net/sf/statsvn/renderer/package.html" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="checkstyle"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_Main.java" module="statsvn"
        path="net/sf/statsvn/Main.java" project="StatSvn">
        <result date="2006-11-14" statvalue="19" type="checkstyle"/>
        <result date="2006-11-14" statvalue="1" type="findbugs"/>
        <result date="2006-11-14" statvalue="31" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="55" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="19" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="findbugs"/>
        <result date="2006-11-15" statvalue="31" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="55" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="19" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="findbugs"/>
        <result date="2006-11-16" statvalue="31" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="55" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="19" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="findbugs"/>
        <result date="2006-11-17" statvalue="31" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="55" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="12" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="findbugs"/>
        <result date="2006-11-18" statvalue="31" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="55" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="12" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="findbugs"/>
        <result date="2006-11-19" statvalue="31" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="55" type="cobertura-branch"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_Messages.java"
        module="statsvn" path="net/sf/statsvn/Messages.java" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-14" statvalue="40" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="40" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="1" type="checkstyle"/>
        <result date="2006-11-16" statvalue="40" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="1" type="checkstyle"/>
        <result date="2006-11-17" statvalue="40" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="33" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="33" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_ant_StatCvsTask.java"
        module="statsvn" path="net/sf/statsvn/ant/StatCvsTask.java" project="StatSvn">
        <result date="2006-11-14" statvalue="9" type="checkstyle"/>
        <result date="2006-11-15" statvalue="9" type="checkstyle"/>
        <result date="2006-11-16" statvalue="9" type="checkstyle"/>
        <result date="2006-11-17" statvalue="9" type="checkstyle"/>
        <result date="2006-11-18" statvalue="2" type="checkstyle"/>
        <result date="2006-11-19" statvalue="2" type="checkstyle"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_input_Builder.java"
        module="statsvn" path="net/sf/statsvn/input/Builder.java" project="StatSvn">
        <result date="2006-11-14" statvalue="14" type="checkstyle"/>
        <result date="2006-11-14" statvalue="1" type="findbugs"/>
        <result date="2006-11-14" statvalue="92" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="94" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="14" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="findbugs"/>
        <result date="2006-11-15" statvalue="92" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="94" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="14" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="findbugs"/>
        <result date="2006-11-16" statvalue="92" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="94" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="7" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="findbugs"/>
        <result date="2006-11-17" statvalue="92" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="94" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="1" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="findbugs"/>
        <result date="2006-11-18" statvalue="91" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="94" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="1" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="findbugs"/>
        <result date="2006-11-19" statvalue="91" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="94" type="cobertura-branch"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_input_CacheBuilder.java"
        module="statsvn" path="net/sf/statsvn/input/CacheBuilder.java" project="StatSvn">
        <result date="2006-11-14" statvalue="16" type="checkstyle"/>
        <result date="2006-11-14" statvalue="61" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="45" type="cobertura-branch"/>
        <result date="2006-11-14" statvalue="1" type="pmd"/>
        <result date="2006-11-15" statvalue="2" type="checkstyle"/>
        <result date="2006-11-15" statvalue="58" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="46" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="2" type="checkstyle"/>
        <result date="2006-11-16" statvalue="58" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="46" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="2" type="checkstyle"/>
        <result date="2006-11-17" statvalue="58" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="46" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="2" type="checkstyle"/>
        <result date="2006-11-18" statvalue="61" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="47" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="2" type="checkstyle"/>
        <result date="2006-11-19" statvalue="61" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="47" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_CommitListBuilder.java"
        module="statsvn"
        path="net/sf/statsvn/input/CommitListBuilder.java" project="StatSvn">
        <result date="2006-11-14" statvalue="3" type="checkstyle"/>
        <result date="2006-11-14" statvalue="96" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="3" type="checkstyle"/>
        <result date="2006-11-15" statvalue="96" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="3" type="checkstyle"/>
        <result date="2006-11-16" statvalue="96" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="2" type="checkstyle"/>
        <result date="2006-11-17" statvalue="96" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="96" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="96" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_EmptyRepositoryException.java"
        module="statsvn"
        path="net/sf/statsvn/input/EmptyRepositoryException.java" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-14" statvalue="50" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="50" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="50" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="50" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="50" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="50" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_input_FileBuilder.java"
        module="statsvn" path="net/sf/statsvn/input/FileBuilder.java" project="StatSvn">
        <result date="2006-11-14" statvalue="33" type="checkstyle"/>
        <result date="2006-11-14" statvalue="86" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="88" type="cobertura-branch"/>
        <result date="2006-11-14" statvalue="1" type="pmd"/>
        <result date="2006-11-15" statvalue="32" type="checkstyle"/>
        <result date="2006-11-15" statvalue="86" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="24" type="checkstyle"/>
        <result date="2006-11-16" statvalue="87" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="91" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="7" type="checkstyle"/>
        <result date="2006-11-17" statvalue="87" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="91" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="5" type="checkstyle"/>
        <result date="2006-11-18" statvalue="88" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="88" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="5" type="checkstyle"/>
        <result date="2006-11-19" statvalue="88" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="88" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_LogSyntaxException.java"
        module="statsvn"
        path="net/sf/statsvn/input/LogSyntaxException.java" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_NoLineCountException.java"
        module="statsvn"
        path="net/sf/statsvn/input/NoLineCountException.java" project="StatSvn">
        <result date="2006-11-14" statvalue="1" type="checkstyle"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="1" type="checkstyle"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_RepositoryFileManager.java"
        module="statsvn"
        path="net/sf/statsvn/input/RepositoryFileManager.java" project="StatSvn">
        <result date="2006-11-14" statvalue="5" type="checkstyle"/>
        <result date="2006-11-14" statvalue="3" type="findbugs"/>
        <result date="2006-11-14" statvalue="41" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="66" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="5" type="checkstyle"/>
        <result date="2006-11-15" statvalue="3" type="findbugs"/>
        <result date="2006-11-15" statvalue="41" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="66" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="4" type="checkstyle"/>
        <result date="2006-11-16" statvalue="3" type="findbugs"/>
        <result date="2006-11-16" statvalue="41" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="66" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="4" type="checkstyle"/>
        <result date="2006-11-17" statvalue="3" type="findbugs"/>
        <result date="2006-11-17" statvalue="41" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="66" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="1" type="findbugs"/>
        <result date="2006-11-18" statvalue="41" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="66" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="1" type="findbugs"/>
        <result date="2006-11-19" statvalue="41" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="66" type="cobertura-branch"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_input_RevisionData.java"
        module="statsvn" path="net/sf/statsvn/input/RevisionData.java" project="StatSvn">
        <result date="2006-11-14" statvalue="18" type="checkstyle"/>
        <result date="2006-11-14" statvalue="3" type="findbugs"/>
        <result date="2006-11-15" statvalue="18" type="checkstyle"/>
        <result date="2006-11-15" statvalue="3" type="findbugs"/>
        <result date="2006-11-16" statvalue="7" type="checkstyle"/>
        <result date="2006-11-16" statvalue="3" type="findbugs"/>
        <result date="2006-11-17" statvalue="3" type="checkstyle"/>
        <result date="2006-11-17" statvalue="3" type="findbugs"/>
        <result date="2006-11-18" statvalue="2" type="checkstyle"/>
        <result date="2006-11-18" statvalue="3" type="findbugs"/>
        <result date="2006-11-19" statvalue="2" type="checkstyle"/>
        <result date="2006-11-19" statvalue="3" type="findbugs"/>
    </file>
    <file id="StatSvn-statsvn-net_sf_statsvn_input_SvnLogBuilder.java"
        module="statsvn" path="net/sf/statsvn/input/SvnLogBuilder.java" project="StatSvn">
        <result date="2006-11-14" statvalue="12" type="checkstyle"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="12" type="checkstyle"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="6" type="checkstyle"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="1" type="checkstyle"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="1" type="checkstyle"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="1" type="checkstyle"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_SvnLogfileParser.java"
        module="statsvn"
        path="net/sf/statsvn/input/SvnLogfileParser.java" project="StatSvn">
        <result date="2006-11-14" statvalue="34" type="checkstyle"/>
        <result date="2006-11-14" statvalue="1" type="findbugs"/>
        <result date="2006-11-14" statvalue="79" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-14" statvalue="6" type="pmd"/>
        <result date="2006-11-15" statvalue="34" type="checkstyle"/>
        <result date="2006-11-15" statvalue="1" type="findbugs"/>
        <result date="2006-11-15" statvalue="79" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="6" type="pmd"/>
        <result date="2006-11-16" statvalue="34" type="checkstyle"/>
        <result date="2006-11-16" statvalue="1" type="findbugs"/>
        <result date="2006-11-16" statvalue="79" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="6" type="pmd"/>
        <result date="2006-11-17" statvalue="29" type="checkstyle"/>
        <result date="2006-11-17" statvalue="1" type="findbugs"/>
        <result date="2006-11-17" statvalue="79" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="6" type="pmd"/>
        <result date="2006-11-18" statvalue="18" type="checkstyle"/>
        <result date="2006-11-18" statvalue="1" type="findbugs"/>
        <result date="2006-11-18" statvalue="79" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="6" type="pmd"/>
        <result date="2006-11-19" statvalue="18" type="checkstyle"/>
        <result date="2006-11-19" statvalue="1" type="findbugs"/>
        <result date="2006-11-19" statvalue="79" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="90" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="6" type="pmd"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_SvnXmlCacheFileHandler.java"
        module="statsvn"
        path="net/sf/statsvn/input/SvnXmlCacheFileHandler.java" project="StatSvn">
        <result date="2006-11-14" statvalue="8" type="checkstyle"/>
        <result date="2006-11-14" statvalue="88" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="8" type="checkstyle"/>
        <result date="2006-11-15" statvalue="88" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="3" type="checkstyle"/>
        <result date="2006-11-16" statvalue="91" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="3" type="checkstyle"/>
        <result date="2006-11-17" statvalue="91" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="88" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-19" statvalue="88" type="cobertura-line"/>
        <result date="2006-11-19" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="StatSvn-statsvn-net_sf_statsvn_input_SvnXmlLogFileHandler.java"
        module="statsvn"
        path="net/sf/statsvn/input/SvnXmlLogFileHandler.java" project="StatSvn">
        <result date="2006-11-14" statvalue="10" type="checkstyle"/>
        <result date="2006-11-14" statvalue="90" type="cobertura-line"/>
        <result date="2006-11-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-14" statvalue="1" type="pmd"/>
        <result date="2006-11-15" statvalue="10" type="checkstyle"/>
        <result date="2006-11-15" statvalue="90" type="cobertura-line"/>
        <result date="2006-11-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-15" statvalue="1" type="pmd"/>
        <result date="2006-11-16" statvalue="8" type="checkstyle"/>
        <result date="2006-11-16" statvalue="90" type="cobertura-line"/>
        <result date="2006-11-16" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-16" statvalue="1" type="pmd"/>
        <result date="2006-11-17" statvalue="8" type="checkstyle"/>
        <result date="2006-11-17" statvalue="90" type="cobertura-line"/>
        <result date="2006-11-17" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-17" statvalue="1" type="pmd"/>
        <result date="2006-11-18" statvalue="89" type="cobertura-line"/>
        <result date="2006-11-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-18" statvalue="1" type="pmd"/>